# 单机模式配置
spring:
  redis:
    host: localhost  # IP
    port: 6379  # 端口号
    password: wgf123  # 密码
    timeout: 10000
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 20 # 连接池中的最大空闲连接


# 哨兵模式配置
#spring:
#  redis:
#    database: 0
#    password: wgf123
#    connect-timeout: 3000   # 连接超时时间（毫秒）
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379  # 多个哨兵逗号隔开
#    lettuce: # Redis的Java驱动包,使用lettuce连接池
#      pool:
#        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10    # 连接池中的最大空闲连接 (默认为8)
#        min-idle: 0     # 连接池中的最小空闲连接


# 集群模式配置
#spring:
#  redis:
#    database: 0
#    password: wgf123
#    connect-timeout: 3000   # 连接超时时间（毫秒）
#    cluster:
#      nodes: 127.0.0.1:6400,127.0.0.1:6401,127.0.0.1:7400,127.0.0.1:7401,127.0.0.1:8400,127.0.0.1:8401
#    lettuce: # Redis的Java驱动包,使用lettuce连接池
#      pool:
#        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8    # 连接池中的最大空闲连接 (默认为8)
#        min-idle: 0     # 连接池中的最小空闲连接



  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher